services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vision-cine-frontend
    working_dir: /app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vision-cine-backend
    working_dir: /app
    ports:
      - '8000:8000'
    environment:
      - APP_ENV=prod
      - DATABASE_URL=mysql://root:123456@mariadb:3306/db_symfony?serverVersion=10.8.8-MariaDB&charset=utf8mb4
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.8.8
    container_name: vision-cine-db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db_symfony
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: vision-cine-phpmyadmin
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - '8080:80'
    depends_on:
      - mariadb

volumes:
  db_data:
