services:
  frontend:
    image: node:18
    container_name: vision-cine-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: vision-cine-backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - '8000:8000'
    command: sh -c "
      composer install &&
      php bin/console doctrine:migrations:migrate --no-interaction &&
      php -S 0.0.0.0:8000 -t public"
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://root:123456@mariadb:3306/db_symfony?serverVersion=10.8.8-MariaDB&charset=utf8mb4
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.8.8
    container_name: vision-cine-db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db_symfony
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: vision-cine-phpmyadmin
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - '8080:80'
    depends_on:
      - mariadb

volumes:
  db_data:
