api_platform:
    title: Hello API Platform
    version: 1.0.0
    # Good defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            standard_patch: true
        pagination_items_per_page: 10
        pagination_client_items_per_page: true
        collection:
            pagination:
                items_per_page_parameter_name: 'itemsPerPage'

    graphql:
        collection:
            pagination:
                enabled: true